# name: Playwright Tests
# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]
# jobs:
#   test:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - uses: actions/setup-node@v4
#       with:
#         node-version: lts/*
#     - name: Install dependencies
#       run: npm ci
#     - name: Install Playwright Browsers
#       run: npx playwright install --with-deps
#     - name: Run Playwright tests
#       run: npx playwright test
#     - uses: actions/upload-artifact@v4
#       if: ${{ !cancelled() }}
#       with:
#         name: playwright-report
#         path: playwright-report/
#         retention-days: 30
 
# name: Playwright Tests

# on:
#   push:
#     branches: [main, master]
#   pull_request:
#     branches: [main, master]
#   # workflow_dispatch:

#   workflow_dispatch:
#     inputs:
#       testType:
#         description: "Select test type"
#         required: true
#         default: "smoke"
#         type: choice
#         options:
#           - smoke
#           - sanity
#           - regression
#           - all

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20
#           cache: npm

#       - name: Install dependencies
#         run: npm ci

#       - name: Install Playwright browsers
#         run: npx playwright install --with-deps

      
#       - name: Run Playwright tests
#         run: |
#           if [ "${{ github.event.inputs.testType }}" == "all" ] || [ -z "${{ github.event.inputs.testType }}" ]; then
#             npx playwright test
#           else
#             npx playwright test --grep "@${{ github.event.inputs.testType }}"
#           fi

#       # - name: Run Playwright tests
#       #   run: npx playwright test

#       - name: Upload Playwright HTML report
#         if: always()
#         uses: actions/upload-artifact@v4
#         with:
#           name: playwright-report
#           path: playwright-report/
#           retention-days: 30


name: Playwright Tests
 
on:
  workflow_dispatch:
    inputs:
      test_env:
        description: "Select environment"
        required: true
        default: "qa"
        type: choice
        options:
          - qa
          - DEV
      testType:
        description: "Select Test Suite"
        required: true
        type: choice
        default: "all"
        options:
          - smoke
          - regression
          - all
 
  push:
    branches: [main, master, Final_Assignment]
 
  pull_request:
    branches: [main, master, Final_Assignment]
 
jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.test_env || 'qa' }}
 
    env:
      TEST_ENV: ${{ github.event.inputs.test_env || 'qa' }}
      BASE_URL: ${{ secrets.BASE_URL }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
 
      - name: Install dependencies
        run: npm ci
 
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
 
      - name: Run Playwright tests
        run: |
          if [ "${{ github.event.inputs.testType || 'all' }}" = "smoke" ]; then
            npx playwright test --grep "@smoke"
          elif [ "${{ github.event.inputs.testType || 'all' }}" = "regression" ]; then
            npx playwright test --grep "@regression"
          else
            npx playwright test
          fi
 
      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ env.TEST_ENV }}
          path: playwright-report/
          retention-days: 30
 